In [175]:
import pandas as pd
import sqlite3
import requests
import os
from dotenv import load_dotenv

#### Q1 - Working with CSV File

In [176]:
# Load CSV Dataset

students = pd.read_csv('students.csv')

In [177]:
# Display first 5 rows, column name, and shape

print(f'First 5 Rows: \n{students.head()}\n')

print(f'Student Columns Names: {students.columns}\n')

print(f'Shape: {students.shape}\n')

First 5 Rows:
           name  age  marks
0  Aarav Sharma   20     85
1   Priya Patel   21     92
2   Ishan Gupta   19     78
3  Ananya Singh   22     88
4   Vihaan Shah   20     95

Student Columns Names: Index(['name', 'age', 'marks'], dtype='str')

Shape: (20, 3)

In [178]:
# Filtered (marks > 70)

mark_gte_70 = students[students['marks']>70]
print(f'Filtered (marks > 70): \n{mark_gte_70}')

Filtered (marks > 70):
                name  age  marks
0       Aarav Sharma   20     85
1        Priya Patel   21     92
2        Ishan Gupta   19     78
3       Ananya Singh   22     88
4        Vihaan Shah   20     95
5        Meera Reddy   21     74
6        Arjun Verma   19     81
9        Kriti Joshi   21     91
10       Aditya Bose   19     76
12    Siddharth Nair   20     93
13         Diya Iyer   21     82
15  Ishani Choudhury   22     96
17        Tanvi Jain   21     87
19      Sneha Kapoor   22     90

In [179]:
# Save the CSV

mark_gte_70.to_csv('filtered_students.csv', index=False)

#### Q2 - Working with JSON File

In [180]:
# Load JSON Dataset

employee = pd.read_json('employee.json')

In [181]:
# Display first 5 rows, column name, and shape

print(f'First 5 Rows: \n{employee.head()}\n')

print(f'Student Columns Names: {employee.columns}\n')

print(f'Shape: {employee.shape}\n')

First 5 Rows:
    id          name department
0  101  Aarav Sharma         IT
1  102   Priya Patel         HR
2  103   Ishan Gupta    Finance
3  104  Ananya Singh  Marketing
4  105   Vihaan Shah         IT

Student Columns Names: Index(['id', 'name', 'department'], dtype='str')

Shape: (20, 3)

In [182]:
# Filtered (department == IT)

IT = employee[employee['department']=='IT']
print(f'Filtered (department = IT): \n{IT}')

Filtered (department = IT):
     id          name department
0   101  Aarav Sharma         IT
4   105   Vihaan Shah         IT
9   110   Kriti Joshi         IT
14  115    Karan Gill         IT
19  120  Sneha Kapoor         IT

In [183]:
# Save the JSON

IT.to_json('filtered_employee.json', orient='records', indent=2)

#### Q3 - Working with SQL File

In [184]:
# Load SQL Dataset

conn = sqlite3.connect('employees.db')

employees = pd.read_sql("SELECT * FROM employees", conn)

In [185]:
# Display first 10 rows, column name, and shape

print(f'First 10 Rows: \n{employees.head(10)}\n')

print(f'Student Columns Names: {employees.columns}\n')

print(f'Shape: {employees.shape}\n')

First 10 Rows:
   id            name  age  department
0   1    Aarav Sharma   28          IT
1   2     Priya Patel   32          HR
2   3     Ishan Gupta   25     Finance
3   4    Ananya Singh   29   Marketing
4   5     Vihaan Shah   35          IT
5   6     Meera Reddy   27  Operations
6   7     Arjun Verma   31     Finance
7   8  Sanya Malhotra   24          HR
8   9       Rohan Das   30       Sales
9  10     Kriti Joshi   26          IT

Student Columns Names: Index(['id', 'name', 'age', 'department'], dtype='str')

Shape: (20, 4)

In [186]:
# Filtered (age > 25)

age_gte_25 = employees[employees['age']>25]
print(f'Filtered (age > 25): \n{age_gte_25}')

Filtered (age > 25):
    id              name  age  department
0    1      Aarav Sharma   28          IT
1    2       Priya Patel   32          HR
3    4      Ananya Singh   29   Marketing
4    5       Vihaan Shah   35          IT
5    6       Meera Reddy   27  Operations
6    7       Arjun Verma   31     Finance
8    9         Rohan Das   30       Sales
9   10       Kriti Joshi   26          IT
10  11       Aditya Bose   33   Marketing
11  12         Zara Khan   29  Operations
12  13    Siddharth Nair   28       Sales
13  14         Diya Iyer   34     Finance
14  15        Karan Gill   27          IT
15  16  Ishani Choudhury   31          HR
16  17       Rahul Mehta   26       Sales
17  18        Tanvi Jain   30   Marketing
18  19    Manav Malhotra   32  Operations

In [187]:
# Save the SQL

conn1 = sqlite3.connect('filtered_employees.db')

age_gte_25.to_sql('filtered_employees', conn1, if_exists='replace', index=False)

17

In [188]:
# Close connections

conn.close()
conn1.close()

#### Q4 - Fetching Data from an API

In [189]:
# Fetch from API

load_dotenv()
api_key = os.environ.get("API_KEY")

url = "https://rest.coincap.io/v3/markets"
headers = {"Authorization": f"Bearer {api_key}"}

response = requests.get(url, headers=headers)

In [190]:
# Converted to DF

if response.status_code == 200:
    data = response.json()
    data = data['data']

    coins = pd.DataFrame(data)
else:
    print("Error Code: ", response.status_code)

In [191]:
# Display first 5 rows, column name, and shape

print(f'First 5 Rows: \n{coins.head()}\n')

print(f'Student Columns Names: {coins.columns}\n')

print(f'Shape: {coins.shape}\n')

First 5 Rows:
  exchangeId rank baseSymbol        baseId quoteSymbol               quoteId  \
0       gate    1       XAUT   tether-gold        USDT                tether
1    orangex    2        SUI           sui        USDT                tether
2    bithumb    3        ENJ    enjin-coin         KRW      south-korean-won
3        p2b    4        BNB  binance-coin         USD  united-states-dollar
4     grovex    5        XRP           xrp       FDUSD     first-digital-usd

                priceQuote                 priceUsd  \
0  4661.600000000000363798  4660.300000000000181899
1     0.971700000000000008     0.971700000000000008
2    36.179999999999999716     0.024360000000000000
3   642.190000000000054570   642.090000000000031832
4     1.452599999999999891     1.450900000000000079

                 volumeUsd24Hr percentExchangeVolume tradesCount24Hr  \
0  37229410.058849997818470001                 34.13            None
1  18978992.729699999094009399                 17.40            None
2   7758923.453604364767670631                  7.11            None
3   6822820.730130000971257687                  6.26            None
4   6371232.149070900864899158                  5.84            None

         updated
0  1773989971071
1  1773989963449
2  1773989971580
3  1773989971075
4  1773989973428

Student Columns Names: Index(['exchangeId', 'rank', 'baseSymbol', 'baseId', 'quoteSymbol', 'quoteId',
       'priceQuote', 'priceUsd', 'volumeUsd24Hr', 'percentExchangeVolume',
       'tradesCount24Hr', 'updated'],
      dtype='str')

Shape: (100, 12)

In [192]:
# Filtered (exchangeId = binance and coinex)

binance_coinex = pd.DataFrame(coins[(coins['exchangeId'] == 'binance') | (coins['exchangeId'] == 'coinex')])
binance_coinex.head()

,exchangeId,rank,baseSymbol,baseId,quoteSymbol,quoteId,priceQuote,priceUsd,volumeUsd24Hr,percentExchangeVolume,tradesCount24Hr,updated
6,binance,7,CAKE,pancakeswap,USDT,tether,1.422499999999999876,1.422499999999999876,2612164.047774999868124723,2.39,None,1773989985982
7,binance,8,ETH,ethereum,U,united-stables,2136.715000000000145519,2136.480000000000018190,2553562.130063999909907579,2.34,None,1773989957470
58,binance,59,NEAR,near-protocol,U,united-stables,1.354999999999999982,1.354524000000000061,41807.925069600001734216,0.04,None,1773989957489
60,binance,61,INJ,injective-protocol,BTC,bitcoin,0.000044705000000000,3.157000000000000028,38022.308169999996607658,0.03,None,1773989985952
73,coinex,74,TAO,bittensor,BTC,bitcoin,0.004229000000000000,298.060000000000002274,7018.935256639600083872,0.01,None,1773989962899

#### Q5 - Data Cleaning Process

In [193]:
# Load CSV Dataset

uncleaned_data = pd.read_csv('uncleaned_data.csv')

In [194]:
# Display first 5 rows, column name, and shape

print(f'First 5 Rows: \n{uncleaned_data.head()}\n')

print(f'Student Columns Names: {uncleaned_data.columns}\n')

print(f'Shape: {uncleaned_data.shape}\n')

First 5 Rows:
    id          name   age  marks department joining_date
0  101  Aarav Sharma  20.0   85.0         IT   2023-01-15
1  102   Priya Patel   NaN   92.0         HR   2023-02-10
2  103   Ishan Gupta  19.0   78.0    FINANCE   2023-01-20
3  104  Ananya Singh  22.0  500.0  Marketing   2023-03-05
4  105   Vihaan Shah  20.0   95.0         it   2023-01-12

Student Columns Names: Index(['id', 'name', 'age', 'marks', 'department', 'joining_date'], dtype='str')

Shape: (20, 6)

In [195]:
# Before Cleaning

print(f'Uncleaned Data: \n{uncleaned_data.head()}\n')

Uncleaned Data:
    id          name   age  marks department joining_date
0  101  Aarav Sharma  20.0   85.0         IT   2023-01-15
1  102   Priya Patel   NaN   92.0         HR   2023-02-10
2  103   Ishan Gupta  19.0   78.0    FINANCE   2023-01-20
3  104  Ananya Singh  22.0  500.0  Marketing   2023-03-05
4  105   Vihaan Shah  20.0   95.0         it   2023-01-12

In [196]:
print('Info:')
print(uncleaned_data.info())

Info:
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            20 non-null     int64
 1   name          20 non-null     str
 2   age           18 non-null     float64
 3   marks         19 non-null     float64
 4   department    20 non-null     str
 5   joining_date  19 non-null     str
dtypes: float64(2), int64(1), str(3)
memory usage: 1.1 KB
None

In [197]:
print('\nDescribe:')
print(uncleaned_data[['age', 'marks']].describe())

Describe:
              age       marks
count   18.000000   19.000000
mean    30.777778  104.947368
std     42.268825   96.127504
min     19.000000   65.000000
25%     19.250000   77.000000
50%     21.000000   85.000000
75%     22.000000   91.500000
max    200.000000  500.000000

In [198]:
print('Null Value Count:')
print(uncleaned_data.isnull().sum())

Null Value Count:
id              0
name            0
age             2
marks           1
department      0
joining_date    1
dtype: int64

In [199]:
' As you can see, the dataset has missing values, outliers(marks and age), not standardize(department), and date format. '

' As you can see, the dataset has missing values, outliers(marks and age), not standardize(department), and date format. '

In [200]:
uncleaned_data

     id              name    age  marks  department joining_date
0   101      Aarav Sharma   20.0   85.0          IT   2023-01-15
1   102       Priya Patel    NaN   92.0          HR   2023-02-10
2   103       Ishan Gupta   19.0   78.0     FINANCE   2023-01-20
3   104      Ananya Singh   22.0  500.0   Marketing   2023-03-05
4   105       Vihaan Shah   20.0   95.0          it   2023-01-12
5   106       Meera Reddy   21.0    NaN  Operations   2023-04-01
6   107       Arjun Verma   19.0   81.0     Finance   22-01-2023
7   108    Sanya Malhotra   22.0   89.0          HR   2023-02-15
8   109         Rohan Das  200.0   67.0       Sales   2023-05-10
9   110       Kriti Joshi   21.0   91.0          IT          NaN
10  111       Aditya Bose   19.0   76.0   marketing   2023-03-12
11  112         Zara Khan   22.0   84.0  Operations   2023-04-05
12  113    Siddharth Nair   20.0   93.0       Sales   2023-05-12
13  114         Diya Iyer    NaN   82.0     Finance   2023-01-25
14  115        Karan Gill   19.0   70.0          IT   2023-01-18
15  116  Ishani Choudhury   22.0   96.0          HR   2023-02-20
16  117       Rahul Mehta   26.0   73.0       Sales   2023-05-15
17  118        Tanvi Jain   21.0   87.0   Marketing   2023-03-20
18  119    Manav Malhotra   19.0   65.0  Operations   2023-04-10
19  120      Sneha Kapoor   22.0   90.0          IT   2023-01-22

In [201]:
# Cleaning Process

clean_data = uncleaned_data

# Handled Missing Values
clean_data.fillna({'age': clean_data['age'].median(),'marks': clean_data['marks'].median()},inplace=True)
clean_data.dropna(inplace=True)

In [202]:

# Handled Outliers

def outlier(colname,data):
    q1 = data[colname].quantile(0.25)
    q3 = data[colname].quantile(0.75)
    iqr = q3 - q1

    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    new_data = data[(data[colname] >= lower) & (data[colname] <= upper)]

    return new_data

clean_data = outlier('age', clean_data)
clean_data = outlier('marks', clean_data)

clean_data

     id              name   age  marks  department joining_date
0   101      Aarav Sharma  20.0   85.0          IT   2023-01-15
1   102       Priya Patel  21.0   92.0          HR   2023-02-10
2   103       Ishan Gupta  19.0   78.0     FINANCE   2023-01-20
4   105       Vihaan Shah  20.0   95.0          it   2023-01-12
5   106       Meera Reddy  21.0   85.0  Operations   2023-04-01
6   107       Arjun Verma  19.0   81.0     Finance   22-01-2023
7   108    Sanya Malhotra  22.0   89.0          HR   2023-02-15
10  111       Aditya Bose  19.0   76.0   marketing   2023-03-12
11  112         Zara Khan  22.0   84.0  Operations   2023-04-05
12  113    Siddharth Nair  20.0   93.0       Sales   2023-05-12
13  114         Diya Iyer  21.0   82.0     Finance   2023-01-25
14  115        Karan Gill  19.0   70.0          IT   2023-01-18
15  116  Ishani Choudhury  22.0   96.0          HR   2023-02-20
17  118        Tanvi Jain  21.0   87.0   Marketing   2023-03-20
18  119    Manav Malhotra  19.0   65.0  Operations   2023-04-10
19  120      Sneha Kapoor  22.0   90.0          IT   2023-01-22

In [203]:
# Handled Standardize

clean_data['department'] = clean_data['department'].str.upper()
clean_data

     id              name   age  marks  department joining_date
0   101      Aarav Sharma  20.0   85.0          IT   2023-01-15
1   102       Priya Patel  21.0   92.0          HR   2023-02-10
2   103       Ishan Gupta  19.0   78.0     FINANCE   2023-01-20
4   105       Vihaan Shah  20.0   95.0          IT   2023-01-12
5   106       Meera Reddy  21.0   85.0  OPERATIONS   2023-04-01
6   107       Arjun Verma  19.0   81.0     FINANCE   22-01-2023
7   108    Sanya Malhotra  22.0   89.0          HR   2023-02-15
10  111       Aditya Bose  19.0   76.0   MARKETING   2023-03-12
11  112         Zara Khan  22.0   84.0  OPERATIONS   2023-04-05
12  113    Siddharth Nair  20.0   93.0       SALES   2023-05-12
13  114         Diya Iyer  21.0   82.0     FINANCE   2023-01-25
14  115        Karan Gill  19.0   70.0          IT   2023-01-18
15  116  Ishani Choudhury  22.0   96.0          HR   2023-02-20
17  118        Tanvi Jain  21.0   87.0   MARKETING   2023-03-20
18  119    Manav Malhotra  19.0   65.0  OPERATIONS   2023-04-10
19  120      Sneha Kapoor  22.0   90.0          IT   2023-01-22

In [204]:
# Handled Date Format

clean_data['joining_date'] = pd.to_datetime(clean_data['joining_date'],format='mixed')
clean_data

     id              name   age  marks  department joining_date
0   101      Aarav Sharma  20.0   85.0          IT   2023-01-15
1   102       Priya Patel  21.0   92.0          HR   2023-02-10
2   103       Ishan Gupta  19.0   78.0     FINANCE   2023-01-20
4   105       Vihaan Shah  20.0   95.0          IT   2023-01-12
5   106       Meera Reddy  21.0   85.0  OPERATIONS   2023-04-01
6   107       Arjun Verma  19.0   81.0     FINANCE   2023-01-22
7   108    Sanya Malhotra  22.0   89.0          HR   2023-02-15
10  111       Aditya Bose  19.0   76.0   MARKETING   2023-03-12
11  112         Zara Khan  22.0   84.0  OPERATIONS   2023-04-05
12  113    Siddharth Nair  20.0   93.0       SALES   2023-05-12
13  114         Diya Iyer  21.0   82.0     FINANCE   2023-01-25
14  115        Karan Gill  19.0   70.0          IT   2023-01-18
15  116  Ishani Choudhury  22.0   96.0          HR   2023-02-20
17  118        Tanvi Jain  21.0   87.0   MARKETING   2023-03-20
18  119    Manav Malhotra  19.0   65.0  OPERATIONS   2023-04-10
19  120      Sneha Kapoor  22.0   90.0          IT   2023-01-22

In [205]:
# Exported Clean CSV

clean_data.to_csv('cleaned_data.csv', index=False)