In [29]:
import pandas as pd
import seaborn as sns

#### Q1 - Planning a Data Science Project

In [30]:
# Dataset

titanic = pd.DataFrame(sns.load_dataset('titanic'))
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
# Project Goal

' Project Goal is to find which type of group or individual had more chance to survive. '

In [31]:
# Data Science Pipeline

pipeline = {
    'Step 1': 'Data Collection',
    'Step 2': 'Data Cleaning',
    'Step 3': 'EDA',
    'Step 4': 'Analysis & Modeling',
    'Step 5': 'Communicate',
}

for i,j in pipeline.items():
    print(f'{i}: {j}')

Step 1: Data Collection
Step 2: Data Cleaning
Step 3: EDA
Step 4: Analysis & Modeling
Step 5: Communicate

#### Q2 - Framing a Machine Learning Problem

In [32]:
# Dataset

titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
# Define Features and Target

' What is the input (features)? -> sex, age, pclass, deck, alone, who '
' What is the output (target)? ->  survived '
' What kind of ML problem is this? -> Classification '

In [34]:
# Problem Structure

structure = {
    'Dataset': 'Titanic',
    'Features': ['Sex', 'Age', 'PClass', 'Deck', 'Alone', 'Who'],
    'Target': 'Survived',
    'ML_Type': 'Classification'
}

for i,j in structure.items():
    print(f'{i}: {j}')

Dataset: Titanic
Features: ['Sex', 'Age', 'PClass', 'Deck', 'Alone', 'Who']
Target: Survived
ML_Type: Classification