In [56]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import KBinsDiscretizer, Binarizer

#### Q1 - Binning Discretization

In [57]:
# Created dataset

np.random.seed(9009)
df = pd.DataFrame({
    'Age' : np.random.randint(18,70, 100)
})
display(df.head())

   Age
0   54
1   28
2   54
3   19
4   50

In [58]:
# Apply

df['Age_group'] = pd.cut(
    df['Age'],
    bins=[17,30,50,70],
    labels=['Young','Middle','Senior'],
    right=True
)
display(df.head(10))

   Age Age_group
0   54    Senior
1   28     Young
2   54    Senior
3   19     Young
4   50    Middle
5   41    Middle
6   63    Senior
7   66    Senior
8   64    Senior
9   50    Middle

In [59]:
# Counts

print(df['Age_group'].value_counts().sort_index())

Age_group
Young     19
Middle    41
Senior    40
Name: count, dtype: int64

#### Q2 - Binarization

In [60]:
# Created dataset

df = pd.DataFrame({
    'Income' : np.random.randint(20000,100000, 100)
})
display(df.head())

   Income
0   63102
1   75107
2   47144
3   82877
4   28145

In [61]:
# Apply

inc_bin = Binarizer(threshold=50000)
df['Income_bin'] = inc_bin.fit_transform(df[['Income']])
display(df.head(10))

   Income  Income_bin
0   63102           1
1   75107           1
2   47144           0
3   82877           1
4   28145           0
5   39604           0
6   52270           1
7   39002           0
8   68133           1
9   77001           1

In [62]:
print(df['Income_bin'].value_counts().sort_index())

Income_bin
0    41
1    59
Name: count, dtype: int64

#### Q3 - Quantile Binning

In [63]:
# Created dataset

df = pd.DataFrame({
    'Income' : np.random.lognormal(10,0.5,100)
})
display(df.head())

         Income
0  21085.131545
1  19762.436095
2  15327.297909
3  19749.618540
4  19502.666140

In [64]:
# Apply

inc_bin = KBinsDiscretizer(n_bins = 4, encode = 'ordinal', strategy='quantile',quantile_method='averaged_inverted_cdf')
df['Income_bin'] = inc_bin.fit_transform(df[['Income']])
display(df.head(10))

         Income  Income_bin
0  21085.131545         2.0
1  19762.436095         1.0
2  15327.297909         0.0
3  19749.618540         1.0
4  19502.666140         1.0
5  15560.847818         0.0
6  13193.237808         0.0
7  28449.380366         2.0
8  25119.640873         2.0
9  26328.460319         2.0

In [65]:

print(df['Income_bin'].value_counts().sort_index())

Income_bin
0.0    25
1.0    25
2.0    25
3.0    25
Name: count, dtype: int64

#### Q4 - K-Means Binning

In [66]:
# Created dataset

df = pd.DataFrame({
    'SpendingScore': np.random.rand(100)
})
display(df.head())

   SpendingScore
0       0.968797
1       0.630387
2       0.582824
3       0.009175
4       0.955172

In [68]:
# Apply

ss_bin = KBinsDiscretizer(n_bins = 4, encode = 'ordinal', strategy='kmeans')
df['SpendingScore_bin'] = ss_bin.fit_transform(df[['SpendingScore']])
display(df.head(10))

   SpendingScore  SpendingScore_bin
0       0.968797                3.0
1       0.630387                2.0
2       0.582824                2.0
3       0.009175                0.0
4       0.955172                3.0
5       0.209364                0.0
6       0.068821                0.0
7       0.522540                2.0
8       0.727429                2.0
9       0.081891                0.0

In [69]:
print(df['SpendingScore_bin'].value_counts().sort_index())

SpendingScore_bin
0.0    21
1.0    31
2.0    23
3.0    25
Name: count, dtype: int64