In [67]:
import seaborn as sns
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.impute import SimpleImputer

#### Q1

In [54]:
# Load dataset

titanic = pd.DataFrame(sns.load_dataset('titanic'))
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [55]:
# Check missing values

print(f'Missing value per column: \n{titanic.isnull().sum()}')

Missing value per column:
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [56]:
# Percentage

pct = titanic.isnull().sum() / len(titanic) * 100

print(f'Missing %: \n{pct[pct>0].sort_values(ascending=False)}')

Missing %:
deck           77.216611
age            19.865320
embarked        0.224467
embark_town     0.224467
dtype: float64

In [57]:
# Drop columns with many Nan value

titanic = titanic.drop('deck', axis='columns')

In [58]:
# Apply imputation

median_imp = SimpleImputer(strategy='median')
titanic[['age']] = median_imp.fit_transform(titanic[['age']])

freq_imp = SimpleImputer(strategy='most_frequent')
titanic[['embarked','embark_town']] = freq_imp.fit_transform(titanic[['embarked','embark_town']])

In [66]:
print(f'Any missing value? \n{titanic.isnull().values.any()}')

Any missing value?
False

#### Q2

In [70]:
# Created df with missing values

df = pd.DataFrame({
    'age':    [25, np.nan, 30, np.nan, 45, 28, np.nan],
    'salary': [50000, 60000, np.nan, 75000, np.nan, 55000, 80000],
    'score':  [np.nan, 85, 90, np.nan, 78, 92, 88]
})
df

    age   salary  score
0  25.0  50000.0    NaN
1   NaN  60000.0   85.0
2  30.0      NaN   90.0
3   NaN  75000.0    NaN
4  45.0      NaN   78.0
5  28.0  55000.0   92.0
6   NaN  80000.0   88.0

In [77]:
# Applied Mean Imputation

mean_imp = SimpleImputer(strategy='mean')
mean_df = pd.DataFrame(mean_imp.fit_transform(df), columns=df.columns)
print(f'Mean imputation: \n{mean_df}')

Mean imputation:
    age   salary  score
0  25.0  50000.0   86.6
1  32.0  60000.0   85.0
2  30.0  64000.0   90.0
3  32.0  75000.0   86.6
4  45.0  64000.0   78.0
5  28.0  55000.0   92.0
6  32.0  80000.0   88.0

In [79]:
# Applied Median Imputation


median_imp = SimpleImputer(strategy='median')
median_df = pd.DataFrame(median_imp.fit_transform(df), columns=df.columns)
print(f'Median imputation: \n{median_df}')

Median imputation:
    age   salary  score
0  25.0  50000.0   88.0
1  29.0  60000.0   85.0
2  30.0  60000.0   90.0
3  29.0  75000.0   88.0
4  45.0  60000.0   78.0
5  28.0  55000.0   92.0
6  29.0  80000.0   88.0

In [80]:
# Comparison

print(f'Before Imputation: \n{df}')

Before Imputation:
    age   salary  score
0  25.0  50000.0    NaN
1   NaN  60000.0   85.0
2  30.0      NaN   90.0
3   NaN  75000.0    NaN
4  45.0      NaN   78.0
5  28.0  55000.0   92.0
6   NaN  80000.0   88.0

In [83]:
print(f'After Imputation(mean): \n{mean_df}')

After Imputation:
    age   salary  score
0  25.0  50000.0   86.6
1  32.0  60000.0   85.0
2  30.0  64000.0   90.0
3  32.0  75000.0   86.6
4  45.0  64000.0   78.0
5  28.0  55000.0   92.0
6  32.0  80000.0   88.0

In [84]:
print(f'After Imputation(median): \n{median_df}')

After Imputation(median):
    age   salary  score
0  25.0  50000.0   88.0
1  29.0  60000.0   85.0
2  30.0  60000.0   90.0
3  29.0  75000.0   88.0
4  45.0  60000.0   78.0
5  28.0  55000.0   92.0
6  29.0  80000.0   88.0

#### Q3