In [42]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer, KNNImputer, MissingIndicator

In [43]:
def random_sample_imp(df ,col, random_state=9009):
    np.random.seed(random_state)

    null_count = df[col].isnull().sum()

    if null_count > 0:
        random_value = df[col].dropna().sample(
            n=null_count,
            replace=True,
            random_state=random_state
        ).values

        df_ = df.copy()
        df_.loc[df_[col].isnull(), col] = random_value

        return df_

    return df

#### Q1 - Missing Indicator + Random Sample Imputation

In [44]:
# df with missing values

df = pd.DataFrame({
    'Age': [20, np.nan, np.nan, np.nan, 21, 38, 23, 25, 19, np.nan, np.nan],
    'Salary': [np.nan, 45000, np.nan, 50000, 34000, np.nan, 30000, 25000, 28000,np.nan, 39000 ],
})
df

     Age   Salary
0   20.0      NaN
1    NaN  45000.0
2    NaN      NaN
3    NaN  50000.0
4   21.0  34000.0
5   38.0      NaN
6   23.0  30000.0
7   25.0  25000.0
8   19.0  28000.0
9    NaN      NaN
10   NaN  39000.0

In [45]:
# Adding missing col

indicator = MissingIndicator(features='missing-only')
indicator_array = indicator.fit_transform(df)

indicator_col = [df.columns[col] + '_Missing' for col in indicator.features_]
indicator_df = pd.DataFrame(indicator_array.astype(int), columns=indicator_col)
indicator_df

    Age_Missing  Salary_Missing
0             0               1
1             1               0
2             1               1
3             1               0
4             0               0
5             0               1
6             0               0
7             0               0
8             0               0
9             1               1
10            1               0

In [46]:
# Random Sample Imputation

imputed_df = df.copy()

for col in df.columns:
    imputed_df = random_sample_imp(imputed_df,col)

imputed_df

     Age   Salary
0   20.0  25000.0
1   25.0  45000.0
2   38.0  34000.0
3   21.0  50000.0
4   21.0  34000.0
5   38.0  50000.0
6   23.0  30000.0
7   25.0  25000.0
8   19.0  28000.0
9   25.0  25000.0
10  21.0  39000.0

In [47]:
# Original vs Imputed

imputed_df = pd.concat([imputed_df,indicator_df], axis=1)
imputed_df

print(f'Orignial DataFrame: \n{df}')
print(f'Imputed DataFrame: \n{imputed_df}')

Orignial DataFrame:
     Age   Salary
0   20.0      NaN
1    NaN  45000.0
2    NaN      NaN
3    NaN  50000.0
4   21.0  34000.0
5   38.0      NaN
6   23.0  30000.0
7   25.0  25000.0
8   19.0  28000.0
9    NaN      NaN
10   NaN  39000.0
Imputed DataFrame:
     Age   Salary  Age_Missing  Salary_Missing
0   20.0  25000.0            0               1
1   25.0  45000.0            1               0
2   38.0  34000.0            1               1
3   21.0  50000.0            1               0
4   21.0  34000.0            0               0
5   38.0  50000.0            0               1
6   23.0  30000.0            0               0
7   25.0  25000.0            0               0
8   19.0  28000.0            0               0
9   25.0  25000.0            1               1
10  21.0  39000.0            1               0